name: Read me Checker 

on:
 push:
   branches:
    - main 

jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
      -uses: actions/checkout@v2
      -name:
        run: |
           ls -ali
           if [! -f README.md ]; then 
           exit 1 
           fi