name: Readme Checker

on:
  pull_request:
    branches:
      - main

jobs:
  Sec-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Lint Python files
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
