name: Read me Checker 

on:
 pull_request:
   branches:
    - main 

jobs:
  Sec-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint Python files
        uses: actions/super-linter@v4
        env:  
            VALIDATE_ALL_CODEBASE: true 
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VALIDATE_PYHON: true
           


           